apiVersion: v1
kind: Secret
metadata:
  name: shop-secret
  labels:
    app: shop
    component: backend
    version: v1
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "mySecurePassword123"
