apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  labels:
    app: shop
    component: backend
    version: v1
    managed-by: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
      component: backend
  template:
    metadata:
      labels:
        app: shop
        component: backend
        version: v1
        tier: application
        role: api-server
    spec:
      initContainers:
        - name: shop-init-container
          image: shop-db-init:latest
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: "Never"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: shop-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      containers:
        - name: shop-crud-container
          image: shop-api:latest
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: shop-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shop-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shop-secret
                  key: POSTGRES_PASSWORD
            - name: SHOP_PORT
              valueFrom:
                configMapKeyRef:
                  name: shop-configmap
                  key: SHOP_PORT
          volumeMounts:
            - name: shop-data
              mountPath: /app/data

          livenessProbe:
            httpGet:
              path: /health
              port: 8001
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8001
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: shop-data
          emptyDir: {}
